<a href="https://colab.research.google.com/github/BhaveshJain1947/Path-Planning/blob/main/SaiyamRL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import pandas as pd
import cv2

In [ ]:
from PIL import Image

img = Image.open('saiyam1.png')
img = img.convert('L')



width, height = img.size


pixels = img.load()
print(width)


1024


In [ ]:
pixel_value = pixels[55, 22]

print('Pixel value: ', pixel_value)

Pixel value:  0


In [ ]:
img

In [ ]:
qvalues=np.zeros((width,height,4))

In [ ]:
actions = ['up', 'right', 'down', 'left']


In [ ]:
rewards = np.full((height, width), -100.)

In [ ]:
for y in range(height):
    for x in range(width):
        pixel_value = pixels[x, y]
        if pixel_value >= 50:  # white pixel
            rewards[y][x] = -1.
        elif pixel_value <= 10:  # black pixel
            rewards[y][x] = -100.
        else:
            rewards[y][x] = 0.

In [ ]:
rewards[63,16]=1000000;

In [ ]:
for row in rewards:
  print(row)

In [ ]:
#define a function that determines if the specified location is a terminal state
def is_terminal_state(current_row_index, current_column_index):
  #if the reward for this location is -1, then it is not a terminal state (i.e., it is a 'white square')
  if rewards[current_row_index, current_column_index] <= 10.:
    return False
  else:
    return True

def get_starting_location():

  current_row_index = 25
  current_column_index = 52
  return current_row_index, current_column_index

#define an epsilon greedy algorithm that will choose which action to take next (i.e., where to move next)
def get_next_action(current_row_index, current_column_index, epsilon):
  #if a randomly chosen value between 0 and 1 is less than epsilon,
  #then choose the most promising value from the Q-table for this state.
  if np.random.random() < epsilon:
    print("H")
    return np.argmax(qvalues[current_row_index, current_column_index])
  else: #choose a random action
    return np.random.randint(4)

#define a function that will get the next location based on the chosen action
def get_next_location(current_row_index, current_column_index, action_index):
  new_row_index = current_row_index
  new_column_index = current_column_index
  if actions[action_index] == 'up' and current_row_index >= 0:
    new_row_index -= 1
  elif actions[action_index] == 'right' and current_column_index < width-1:
    new_column_index += 1
  elif actions[action_index] == 'down' and current_row_index < height - 1:
    new_row_index += 1
  elif actions[action_index] == 'left' and current_column_index >= 0:
    new_column_index -= 1
  return new_row_index, new_column_index

#Define a function that will get the shortest path between any location within the warehouse that
#the robot is allowed to travel and the item packaging location.
def get_shortest_path(start_row_index, start_column_index):
  #return immediately if this is an invalid starting location
  if is_terminal_state(start_row_index, start_column_index):
    return []
  else: #if this is a 'legal' starting location
    current_row_index, current_column_index = start_row_index, start_column_index
    shortest_path = []
    shortest_path.append([current_row_index, current_column_index])
    #continue moving along the path until we reach the goal (i.e., the item packaging location)
    while not is_terminal_state(current_row_index, current_column_index):
      #get the best action to take
      action_index = get_next_action(current_row_index, current_column_index, 1.)
      #move to the next location on the path, and add the new location to the list
      current_row_index, current_column_index = get_next_location(current_row_index, current_column_index, action_index)
      shortest_path.append([current_row_index, current_column_index])
    return shortest_path

AB Q-LEARNING DEFINE KARENGE


In [ ]:
#define training parameters
epsilon = 0.9 #the percentage of time when we should take the best action (instead of a random action)
discount_factor = 0.9 #discount factor for future rewards
learning_rate = 0.9 #the rate at which the AI agent should learn

#run through 1000 training episodes
for episode in range(1000):
  #get the starting location for this episode
  row_index, column_index = get_starting_location()

  #continue taking actions (i.e., moving) until we reach a terminal state
  #(i.e., until we reach the item packaging area or crash into an item storage location)
  while not is_terminal_state(row_index, column_index):
    #choose which action to take (i.e., where to move next)
    action_index = get_next_action(row_index, column_index, epsilon)
    print(2)

    #perform the chosen action, and transition to the next state (i.e., move to the next location)
    old_row_index, old_column_index = row_index, column_index #store the old row and column indexes
    print(123)
    row_index, column_index = get_next_location(row_index, column_index, action_index)

    #receive the reward for moving to the new state, and calculate the temporal difference
    reward = rewards[row_index, column_index]
    old_qvalue = qvalues[old_row_index, old_column_index, action_index]
    temporal_difference = reward + (discount_factor * np.max(qvalues[row_index, column_index])) - old_qvalue

    #update the Q-value for the previous state and action pair
    new_q_value = old_qvalue + (learning_rate * temporal_difference)
    qvalues[old_row_index, old_column_index, action_index] = new_q_value

print('Training complete!')

Streaming output truncated to the last 5000 lines.
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.

In [ ]:
x=get_shortest_path()

In [ ]:
g=cv2.imread(saiyam1.png)
n,m=x.shape()
for i in range(n-1):
  cv2.line(g,x[i][1],x[i][0],(x[i+1][1],x[i+1][0]),(0,255,0),1)

cv2.imshow("model image",g)
cv2.waitKey(0)
cv2.destroyAllWindows()